name: Build 3DS Game

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # This image has 3ds-dev, libctru, and citro3d completely pre-installed!
    container: devkitpro/devkit3ds:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile 3DSX
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make
          
      - name: Upload Finished 3DSX File
        uses: actions/upload-artifact@v4
        with:
          name: my-3ds-game-build
          path: |
            *.3dsx
            *.elf
